---
title: Kristine Chatterjie
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
    permalink: "/:collection/:title/"
    label: work
defaults:
- scope:
    path: ''
  values:
    image: 
exclude:
- package.json
- node_modules
- README.md
- Gemfile
- Gemfile.lock
- ".jekyll-metadata"
- ".sass-cache"
- ".DS_Store"
- package-lock.json
- package.json
- config.codekit3
- LICENSE.txt
plugins:
- jekyll-seo-tag
jekyll-mentions: https://twitter.com
twitter:
  username: _chatterjie
author: Kristine Chatterjie
social:
  name: Kristine Chatterjie
  links:
  - https://twitter.com/_chatterjie
  - https://www.linkedin.com/in/kchatterjie/
  - http://instagram.com/chattyyyy
  - https://www.flickr.com/photos/dearestk/
  - https://www.behance.net/chatterjie
  - https://dribbble.com/kchatterjie
sass:
  sass_dir: _sass
  style: compressed
encoding: utf-8
lang: en-US
logo: "/assets/logo.svg"
description: Kristine Chatterjie is a left-handed artist and designer. Currently a
  UI Designer at ParkWhiz
url: https://kchatterjie.me/
baseurl: 
repo: https://github.com/marcusrelacion/kristinechatterjie.com
email: kchatterjie@gmail.com
