---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
  match: "**/*"
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: _work
  label: Work
  create: all
  match: "**/*"
- type: directory
  path: _uploads
  label: Uploads
  create: all
  match: "**/*"
upload_dir: assets
public_path: "/assets/imgs"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
